services:
  - type: web
    name: proyecto-pima
    env: docker
    plan: free
    autoDeploy: true
    buildCommand: ""      # Render usará el Dockerfile directamente
    startCommand: ""      # Tomará el CMD del Dockerfile
    healthCheckPath: /    # Render hará ping a la ruta raíz
    envVars:
      - key: API_PIMA_URL
        value: "https://apiparagit.onrender.com/precios"
      - key: PYTHONUNBUFFERED
        value: "1"
